---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Setup dnsmasq
      include_role:
        name: dnsmasq

    - git:
        repo: https://github.com/DarrellTang/dotfiles
        dest: "/Users/{{ lookup('env', 'USER') }}/dotfiles"

    - git:
        repo: https://github.com/powerline/fonts
        dest: "/Users/{{ lookup('env', 'USER') }}/fonts"
        depth: 1

    - name: Chdir and install fonts
      shell: "{{ lookup('env', 'HOME') }}fonts/install.sh

    - name: Create a symlinks to dotfiles
      ansible.builtin.file:
        src: "/Users/{{ lookup('env', 'USER') }}/dotfiles/{{ item }}"
        dest: "/Users/{{ lookup('env', 'USER') }}/{{ item }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: staff
        state: link
      with_items:
        - .tmux.conf
        - .zshrc
        - .vimrc
        - .alacritty.yml

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - alacritty
        - virtualbox
        - visual-studio-code

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'awscli',
          'coreutils',
          'curl',
          'dnsmasq',
          'fzf',
          'kubectx',
          'kubernetes-cli',
          'kubernetes-helm',
          'openssl' ,
          'terraform',
          'tmux',
          'unzip',
          'zsh',
        ]
        state: present
        update_homebrew: yes

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure homebrew zsh is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true

    - name: "Install Default Python"
      shell: |
        pip3 install ansible
